export { H1 } from "./H1/H1"
export { H2 } from "./H2/H2"
export { H3 } from "./H3/H3"
export { H4 } from "./H4/H4"
export { H5 } from "./H5/H5"
export { H6 } from "./H6/H6"
export { Label } from "./Label/Label"
export { P1 } from "./P1/P1"
export { P2 } from "./P2/P2"
export { P3 } from "./P3/P3"
export type { HeadingVariant, LabelVariant, ParagraphVariant, TextColor } from "./types"
